name: flutter_swiper
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.1.6
homepage: https://github.com/jzoom/flutter_swiper

dependencies:
  flutter:
    sdk: flutter

  another_transformer_page_view: ^2.0.1
  flutter_page_indicator:
    git:
      url: https://github.com/stobix/flutter_page_indicator.git
      ref: master
#    path: ../flutter_page_indicator

environment:
  sdk: ">=2.0.0-dev.48.0 <3.0.0"
  flutter: ">=0.1.4 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
